### PR TITLE
Use Pydantic to document output types

### LINKED ISSUE #8: Document Return Types with Pydantic
Pydantic (https://pydantic-docs.helpmanual.io/) could simplify documenting the output of each of the functions. It also integrates nicely with FastAPI and we use it in other SDL-related projects.

### PR DESCRIPTION
**Pull request by WardLT**
Fixes #8 

At the high level, we add
- Support for BaseModel output types in the CLI
- Add Pydantic to package requirements
- Add pytest-mock to dev requirements

For each operation in the ADCClient we
1. Add a Pydantic data model for each of the types that are returned
1. Add an example data structure output from ADC
1. Add tests that evaluate the data model
1. Modify the ADCClient operation to return those data type(s)
1. Add tests for the ADCClient, using the data structure example to mock the ADC service

The list of data types to support
- [x] User
- [x] Sample
- [x] Study
- [ ] Investigation
- [ ] Job
- [x] Permission

### CODE REVIEW

**Comment by WardLT** [comment]
@laaraujo , I've finished adding pydantic wrappers to the operations I need to the web services. 

How shall we move forward on wrapping up this PR?

**Comment by laaraujo** [comment]
Awesome work @WardLT !
I'll review this and add whatever is needed either later today or tomorrow. 
Will that work for you?

**Comment by WardLT** [comment]
That works great, thanks!

**Comment by laaraujo-dnt** [comment]
Hey @WardLT , I just changed some very small details. Excellent work.
I'm going to merge this into `dev` but not `staging` (which kinda works like `prod` env for now) since I'd like to keep working on this and make all entities available with Pydantic first.

I went ahead and published a `dev` release with this version of the code so you can have the changes available without any pip+git magic needed.

You can install said dev version with the following command:

`pip install adc-sdk==0.1.3.dev0`

**Review by laaraujo-dnt — APPROVED** [review]
Excellent work.

**Pull request merged**
